### ISSUE TITLE
Node ID

### ISSUE THREAD

**Issue by sweatapp** [GraphStory/neo4j-ios#10]
I was told to ask this question here, so forgive me if this is not the place, but I need to know how to get the ID of a node i want so that i can use the Theo functions. How is this done? i can get the id by returning ID(x) but don't know how to use that with Theo.

**Comment by kwylez** [comment]
I'm away from my computer right now but this afternoon I'll take a look and let you know

**Comment by sweatapp** [comment]
Also I can create nodes, but they do not have a label. I used the following code. I looked in the source and it looks like that is changed, but the readme says to do it the way I am. Which way is best and how do i call it?

let node = Node()
        
        node.setProp("hashedID", propertyValue: user.userID as String)
        node.addLabel("USER")

        theo.createNode(node, completionBlock: {(node2, error) in
            println("new node \(node2)")
            //node2 does not have a label... :(
})

**Comment by kwylez** [comment]
@sweatapp re: the failed label creation can you open a separate issue for that? I want to make sure it is tracked properly. If you run the [unit test](https://github.com/GraphStory/neo4j-ios/blob/master/Source/Theo/TheoTests/Theo_000_RequestTests.swift#L372) for creating a node with a label what is the result?

re: your `ID(x)` issue can you give me a code example of how you are trying to request a particular `id`?

**Comment by sweatapp** [comment]
I will open a new issue for label creation.

As for finding the ID of the node what i need is to be able to execute a cypher to get the id of a node in the DB so that i can use the functions (i.e theo.fetchNode("I NEED TO GET THIS ID", completionBlock: {(node, error) in    
    println("meta in success \(node!.meta) node \(node) error \(error)")
}))

right now i am using the query "MATCH (u {userID: "sweatmobile"}) return ID(u)" to return the node id of a certain node that i found using it's userID. 

Then I need to be able to get that ID(u) value so that i can then pass it to the fetch, delete, update functions because they take node ID's as parameters instead of values of a node. I will need this for relationships as well.

**Comment by kwylez** [comment]
OK. I think I know what your referring to. Right now you would have to execute the theo cypher query and in its collection block grab the dictionary key from the cypher meta  data that holds the ID and then call fetchNode...  

What type method signature would make this easier for you.

**Comment by sweatapp** [comment]
Are you talking about something like this? i have tried to get the value from this. Maybe i don't know how or what.

//Get Internal Node ID from userID
    func getInternalNodeID(userID:NSString, completion: (result: NSString) -> Void)
    {
        let cyperQuery: String = "MATCH (u {userID: \"sweatmobile\"}) return ID(u)"
        let cyperParams: Dictionary<String, AnyObject> = ["user" : "UserObject"]

        
        theo.executeCypher(cyperQuery, params: cyperParams, completionBlock: {(cypher, error) in
            println("response from cypher \(cypher)")
        completion(result: userID)
        })
    }

**Comment by kwylez** [comment]
What is the output from println(cypher....?

**Comment by sweatapp** [comment]
response from cypher Optional(meta description Columns: [ID(u)], data [])

**Comment by kwylez** [comment]
I'll see what I can throw together this week for a fix

**Comment by sweatapp** [comment]
That would be great because at this point my development has essentially stopped. Even something as simple as a new method that gets an I'd based off of a property inputted. I really appreciate your help and your time making Theo.

**Comment by sweatapp** [comment]
Not sure why, but i got back on today and it returned a value now so i can access it using cypher!.data[0].values.array[0]

Not sure why it works now, but I'm glad it is.

**Comment by kwylez** [comment]
Are you using any NSURLCache?

I'm going to try and come up with a method like you suggested.

**Comment by kwylez** [comment]
Closing due to non response
