### ISSUE TITLE
Node Label Not Getting Created

### ISSUE THREAD

**Issue by sweatapp** [GraphStory/neo4j-ios#11]
When i use the function(as defined in the readme)

let node = Node()
let randomString: String = NSUUID.UUID().UUIDString

node.setProp("propertyKey_1", propertyValue: "propertyValue_1" + randomString)
node.setProp("propertyKey_2", propertyValue: "propertyValue_2" + randomString)
node.addLabel("customLabelForNode_" + randomString)

theo.createNode(node, completionBlock: {(node, error) in
    println("new node \(node)")
});

it creates a node just fine, but does not add the label to it so it is just a blank label. Below is an example where i created a user node with label "USER" using the addLabel function, but it didn't add the label to it.

below is my test output that passed
![snip20150522_4](https://cloud.githubusercontent.com/assets/12041100/7780964/4d6939b2-00a3-11e5-8b71-9d39bb193d76.png)

Test Suite 'Selected tests' started at 2015-05-22 22:43:44 +0000
Test Suite 'TheoTests.xctest' started at 2015-05-22 22:43:44 +0000
Test Suite 'Theo_000_RequestTests' started at 2015-05-22 22:43:44 +0000
Test Case '-[TheoTests.Theo_000_RequestTests test_008_succesfullyAddNodeWithLabels]' started.
Test Case '-[TheoTests.Theo_000_RequestTests test_008_succesfullyAddNodeWithLabels]' passed (0.142 seconds).
Test Suite 'Theo_000_RequestTests' passed at 2015-05-22 22:43:44 +0000.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.142 (0.147) seconds
Test Suite 'TheoTests.xctest' passed at 2015-05-22 22:43:44 +0000.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.142 (0.149) seconds
Test Suite 'Selected tests' passed at 2015-05-22 22:43:44 +0000.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.142 (0.154) seconds

**Comment by kwylez** [comment]
I'll need to rerun my unit tests and see what is going on. You are making the right call. What version of Neo4j are you using?

**Comment by sweatapp** [comment]
"node": "https://neo-553a923019293-364459c455.do-stories.graphstory.com:7473/db/data/node",
  "node_index": "https://neo-553a923019293-364459c455.do-stories.graphstory.com:7473/db/data/index/node",
  "relationship_index": "https://neo-553a923019293-364459c455.do-stories.graphstory.com:7473/db/data/index/relationship",
  "extensions_info": "https://neo-553a923019293-364459c455.do-stories.graphstory.com:7473/db/data/ext",
  "relationship_types": "https://neo-553a923019293-364459c455.do-stories.graphstory.com:7473/db/data/relationship/types",
  "batch": "https://neo-553a923019293-364459c455.do-stories.graphstory.com:7473/db/data/batch",
  "cypher": "https://neo-553a923019293-364459c455.do-stories.graphstory.com:7473/db/data/cypher",
  "indexes": "https://neo-553a923019293-364459c455.do-stories.graphstory.com:7473/db/data/schema/index",
  "constraints": "https://neo-553a923019293-364459c455.do-stories.graphstory.com:7473/db/data/schema/constraint",
  "transaction": "https://neo-553a923019293-364459c455.do-stories.graphstory.com:7473/db/data/transaction",
  "node_labels": "https://neo-553a923019293-364459c455.do-stories.graphstory.com:7473/db/data/labels",
  "neo4j_version": "2.1.7"

I am using Graph Story, so this is what was set up.

**Comment by kwylez** [comment]
Ok. I'll look at this as soon as I can.

**Comment by sweatapp** [comment]
I noticed in Cypher.swift there are two functions for creating a node, they are labled with and without label. The one without matches the parameters inputted above, but the function that says create with labels follows this header public func createNode(node: Node, labels: Array<String>, completionBlock: TheoNodeRequestCompletionBlock?) as opposed to public func createNode(node: Node, completionBlock: TheoNodeRequestCompletionBlock?) for no labels, is that the problem? If so how would i properly call that?

**Comment by kwylez** [comment]
There shouldn't any reference for creating a node with or without a label in `Cypher.swift`. [This](https://github.com/GraphStory/neo4j-ios#create-a-node) is the example of creating a node with and without a label. I'm going to verify with the unit test (using Graph Story) that this functionality is still passing

**Comment by kwylez** [comment]
I can confirm that the node is being created but the labels **are not**. I think I see what the problem is. Part of the problem is that the completionBlock will always return nil https://github.com/GraphStory/neo4j-ios/blob/master/Source/Theo/Theo/Client.swift#L332. I'm working on a hotfix for this

**Comment by kwylez** [comment]
After reviewing the REST API docs, after successful creation of labels for a given node the [response is empty](http://neo4j.com/docs/stable/rest-api-node-labels.html). I'm almost finished with updating the method that creates a node with label(s) and will post a fix shortly

**Comment by kwylez** [comment]
@sweatapp I've got this worked out and it is passing my unit tests
![screen shot 2015-05-25 at 10 14 17 pm](https://cloud.githubusercontent.com/assets/233571/7804082/9d9e6cce-032b-11e5-8240-4f2aa98afb79.png)

**Comment by kwylez** [comment]
This has been fixed [https://github.com/GraphStory/neo4j-ios/releases/tag/2.0.1](https://github.com/GraphStory/neo4j-ios/releases/tag/2.0.1)
