### ISSUE TITLE
Cannot create node - returns nil

### ISSUE THREAD

**Issue by DrD00der** [GraphStory/neo4j-ios#13]
I'm setting up Theo for the first time, and a relatively new progammer to both Swift and neo4j so I'm not sure if I'm missing something obvious or not.  I have neo4j server running on my local mac, and when I run my code I get a return of "new node nil" when trying to add a new node.  I have hit set up with a button to add the node (as you'll see below) but cannot get it to add actual data.

Any insight?  Thanks!

    import UIKit
    import Theo

    class FSTableViewController: UITableViewController {
    
    let theo: Client = Client(baseURL: "http://localhost:7474/", user: "neo4j", pass: "******")

    @IBAction func addNewPost(sender: AnyObject) {
        addNode()
    }
    
    //add node with label
    func addNode(){
        let node = Node()
        let randomString: String = NSUUID().UUIDString
        
        node.setProp("propertyKey_1", propertyValue: "propertyValue_1" + randomString)  //property 1
        node.setProp("propertyKey_2", propertyValue: "propertyValue_2" + randomString)  //property 2
        node.addLabel("Test Node" + randomString)    //this adds the label
        
        theo.createNode(node, completionBlock: {(node, error) in
            print("new node \(node)")
        });
    }
}`

**Comment by kwylez** [comment]
What version of Neo4j are you running? Can you print out the `error` variable in the closure?

**Comment by DrD00der** [comment]
Running Neo4j Community Edition 2.3.2
XCode 7.2.1

here is the node, and error printouts:

new node nil
Optional(Error Domain=com.theo.network.error Code=-1011 "(null)" UserInfo={TheoResponse=<NSHTTPURLResponse: 0x7fe7e8c09730> { URL: http://localhost:7474//db/data/node } { status code: 404, headers {
    "Access-Control-Allow-Origin" = "*";
    "Content-Length" = 0;
    Date = "Mon, 29 Feb 2016 15:35:50 GMT";
    Server = "Jetty(9.2.z-SNAPSHOT)";
} }, TheoResponseCode=404, NSLocalizedDescriptionKey=The response was empty, but you received at valid response code})
new node nil
Optional(Error Domain=com.theo.network.error Code=-1 "(null)" UserInfo={TheoResponse=<NSHTTPURLResponse: 0x7fe7e8c09730> { URL: http://localhost:7474//db/data/node } { status code: 404, headers {
    "Access-Control-Allow-Origin" = "*";
    "Content-Length" = 0;
    Date = "Mon, 29 Feb 2016 15:35:50 GMT";
    Server = "Jetty(9.2.z-SNAPSHOT)";
} }, TheoResponseCode=404, NSLocalizedDescriptionKey=There was an error processing the request})

**Comment by DrD00der** [comment]
Looks like I just needed to remove the slash at the end of the http://localhost:7474

Found a similar question in a prior issue here.  Thanks!

**Comment by kwylez** [comment]
Glad you found it. Would it be helpful if the framework warned you of that "/"?

**Comment by DrD00der** [comment]
Definitely would help.  I see I'm not the only one who ran into this problem so an error would be great.

Thanks!

**Comment by kwylez** [comment]
Would it be more efficient to just included it in the README, throw an
exception or just handle it programmatically?

On Thu, Mar 3, 2016 at 10:27 AM, DrD00der <notifications@github.com> wrote:

> Definitely would help. I see I'm not the only one who ran into this
> problem so an error would be great.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GraphStory/neo4j-ios/issues/13#issuecomment-191814188>
> .
>



-- 
Cory Wiles
kwylez@gmail.com
www.corywiles.com | www.twitter.com/kwylez

**Comment by DrD00der** [comment]
The README definitely needs to be updated.  If it's in there, I think that is totally sufficient
1) It's still listing old syntax, such as println instead of print for Swift 2.  Also, to create a random string I had to change that line to: let randomString: String = NSUUID().UUIDString
2) I have another issue that I see was "closed" in a prior issue.  When I create a node, the label does not get created.  It says in a prior issue you fixed this.  Is there a different syntax needed than what's in the readme?  
3) How do I assign the node to a specific type?  In cypher, you create a node with:
CREATE (:Movie { title:"The Matrix",released:1997 })

If I create a node, I can't make the label as described above (title in this example).  I also don't know how to make the node a "Movie".    Am I missing something obvious?

**Comment by kwylez** [comment]
You can create a node with labels using the following unit test example: https://github.com/GraphStory/neo4j-ios/blob/master/Source/Theo/TheoTests/Theo_000_RequestTests.swift#L382

**Comment by kwylez** [comment]
I updated the **README** with your suggestions. Let me know if there is anything else or submitted a PR.

**Comment by kwylez** [comment]
I'm going to close this issue, but if you are still having your cypher query issue then please open a new issue and we'll debug there.

**Comment by DrD00der** [comment]
Thanks

I'm still having problems with node label creation - I'll start a new issue for this.
