### ISSUE TITLE
Problem recognising Client Class

### ISSUE THREAD

**Issue by hunterlins** [GraphStory/neo4j-ios#14]
Hi

After following the steps outlined to add Theo into my Swift project it doesn't recognise the Client class. I've clear the project and still no luck. Can you help?

**Comment by kwylez** [comment]
Can you send me a screenshot of your project setup?

**Comment by hunterlins** [comment]
Hi Cory,

I've tried Theo again and got it working however keep getting a nil from 
trying this query 
<https://github.com/GraphStory/neo4j-ios#execute-a-cypher-query>
My query which I have reworked is inside the cypherQuery func in 
ViewController.swift. I've included a screenshot for the database browser.

For our team project I am not the back end dev, so I'm just looking to 
find out how to make sure I can access the data.

Kind regards,
Lindsey


On 07/03/2016 21:12, Cory D. Wiles wrote:
>
> Can you send me a screenshot of your project setup?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/GraphStory/neo4j-ios/issues/14#issuecomment-193451779>.
>


//
//  ViewController.swift
//  TheoTester
//
//  Created by Lindsey Hunter on 11/03/2016.
//  Copyright © 2016 Hunter. All rights reserved.
//

import UIKit
import Theo

class ViewController: UIViewController {

    let theo: Client = Client(baseURL: "http://localhost:7474", user: "neo4j", pass: "yolo911@")
    
    override func viewDidLoad() {
        super.viewDidLoad()
        theo.fetchNode("0", completionBlock: {(node, error) in
            var thisNode = node!
            print("meta in success \(node!.meta) node \(thisNode) error \(error)")
        })
        cypherQuery()
        // Do any additional setup after loading the view, typically from a nib.
    }

    func cypherQuery() {
        var nameToMatch = "Thomas"
        let cyperQuery: String = "PROFILE MATCH (a {firstname: \(nameToMatch)}) return a;"
        
        let cyperParams: Dictionary<String, AnyObject> = ["user" : "Thomas"]
        
        theo.executeCypher(cyperQuery, params: cyperParams, completionBlock: {(cypher, error) in
            print("response from cyper \(cypher)")
        })
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}

**Comment by kwylez** [comment]
It might be `let cyperQuery: String = "PROFILE MATCH (a {firstname: \(nameToMatch)}) return a;"`

I don't think you need to escape `nameToMatch` and your params `["user" : "Thomas"]` do not match variables in your query. Maybe try `let cyperQuery: String = "PROFILE MATCH (a {firstname: {user}}) return a;"`

**Comment by hunterlins** [comment]
Dear Cory,

I've got it now- thanks for your help. Problem was the Cypher.

Kind regards,
Lindsey

<https://itunes.apple.com/us/app/william-hunter-coach-hire/id1080372146?ls=1&mt=8>
