### ISSUE TITLE
Unit test 001 failing

### ISSUE THREAD

**Issue by niklassaers** [GraphStory/neo4j-ios#16]
Hi,

I'm new to your project, and configured the TheConfig.json to be

{
"username" : "neo4j",
"password" : "thepassword",
"host" : "http://localhost:7474"
}

and ran the unit tests. test_000_successfullyFetchDBMeta succeeds, but then test_001_successfullyFetchNode fails: node is nil and the error says that http://localhost:7474/db/data/node/100 returned 404. I have to agree with it, I cannot find that it should have been created beforehand. Do I need to load some data before running the tests?

I'm running this test on a fresh Neo4J 3.0.4 install with Xcode 7

**Comment by niklassaers** [comment]
Yes, there seems to be some sample data needed. There is a "test #12" for instance that has this Cypher query:

MATCH (u:User {username: {user} }) WITH u MATCH (u)-[:FOLLOWS*0..1]->f WITH DISTINCT f,u MATCH f-[:LASTPOST]-lp-[:NEXTPOST*0..3]-p RETURN p.contentId as contentId, p.title as title, p.tagstr as tagstr, p.timestamp as timestamp, p.url as url, f.username as username, f=u as owner

And the other tests require at least two nodes with ID 100 and 101, where 100 must have a property called title.

It'd be nice if a script to create the necessary data was included, even better if the tests would create what they need and clean up afterwards.

**Comment by niklassaers** [comment]
It looks like this data is part of a sample database used with the book "Practical Neo4j". I didn't find where to get it, though, so I created a test that creates them. Now all tests pass. See pull request #23

**Comment by niklassaers** [comment]
If I add the assert 
`XCTAssertTrue((cypher?.data.count ?? 0) > 0, "Expected at least one result")`
before
`exp.fulfill()`
in test_012_successfullyExecuteCyperRequest, I have a failing test again. I probably misunderstood something of the expected graph structure in test_000_createTestData. Do you have a suggestion, @kwylez ?

**Comment by niklassaers** [comment]
I began cleanup work, and it seems to have been automatically added to the pull request #23. It has a little problem, though, which is that the delete requests get an error back, 409 - Conflict. Haven't quite figured out why I get that, would love input.

**Comment by kwylez** [comment]
@niklassaers I'm going to go ahead and merge the PR's in and then I'll take a look at the other issues you referenced. Once again thanks for all the effort.

**Comment by niklassaers** [comment]
The 409s were due to the relationships not being removed before the nodes were. :-)
