### ISSUE TITLE
Swift 3 exc_bad_instruction - force unwrap of nil?

### ISSUE THREAD

**Issue by lussierm** [GraphStory/neo4j-ios#17]
Hello - newbie so apologies in advance for breaking any norms.

I have added the Theo neo4j-ios module to an Xcode 8 project (Theo only, to test it out).  Used Edit>Convert>To Current Swift Syntax to clean up compiler errors.  Created a simple view controller with button to run the sample 'fetch meta for a graph' code.  Upon compiling I get an "EXC_BAD-INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)" error when I reach:
let task : URLSessionDataTask = self.httpSession.session.dataTask(with: request, completionHandler: {(data: Data?, response: URLResponse?, error: NSError?) -> Void in
in the "func getResource(..." method of Request.swift.

I get the same message at the same point (let task : URLSessionDataTask....) when I attempt to run the "create a node/without labels' sample code.

After searching around I am thinking this might have something to do with a 'force un-wrap of a nil' (an example is at http://stackoverflow.com/questions/28054030/swift-exc-bad-instruction-code-exc-i386-invop-subcode-0x0-with-datataskwith) but I am not that familiar with Swift to be able to get much farther in sorting it out.

Any guidance on how to fix would be great. Files attached (credentials removed from view controller).
[Archive.zip](https://github.com/GraphStory/neo4j-ios/files/531822/Archive.zip)

**Comment by kwylez** [comment]
@lussierm sorry for the late reply. I honestly haven't had much time to look at the bug, but should this week. The code hasn't been converted to Swift 3 (which is on my short list of to-do's) so there is strong possibility that one of the language changes has is the culprit. If you can bear with me for a few more days I'll have a better answer.

**Comment by buidinhduong** [comment]
please convert to swift 3

**Comment by lussierm** [comment]
No worries – thanks for the note.  No rush on my part.

**Comment by lussierm** [comment]
Hello kwylez - how are things coming along?
Thanks...

**Comment by kwylez** [comment]
@lussierm It is coming along well. There is one more issue with the unit tests that I need to fix and then it will be ready to test. I'm hoping to have that done by wednesday.

**Comment by kwylez** [comment]
@lussierm if you want to take a look at it I'm happy to push my branch up

**Comment by lussierm** [comment]
Thanks for the update.  No worries I can wait.

**Comment by lussierm** [comment]
Hello kwylez.  Maybe if you could push up what you have I could have a look over the holidays.  Thanks.

**Comment by lussierm** [comment]
@kwylez Thanks.  Best of the holidays to you!

**Comment by niklassaers** [comment]
Hey, the error is that the code forces a cast of Error to NSError (or was it the other way around?) and that will always fail. So I've sent a pull request #20 that should fix the error you are seeing (on the develop/swift-3 branch). (you're welcome to check out the fork I made for the pull req at https://github.com/niklassaers/neo4j-ios/tree/develop/swift-3 while @kwylez has a chance to review the pull request)
