### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by MasterSwift** [GraphStory/neo4j-ios#18]
Wondering you have plans to make this available for Swift Package Manager.

**Comment by funkatron** [comment]
I'll let @kwylez comment beyond this, but Swift 3 work is in https://github.com/GraphStory/neo4j-ios/tree/develop/swift-3

**Comment by kwylez** [comment]
@MasterSwift I do have plans to make this available through SPM. I don't have a time table set, but I'm hopeful to have it by first of February of 2017

**Comment by niklassaers** [comment]
@kwylez If you haven't started yet, I'll volunteer. I need it together with Vapor so am planning to do the work this week

**Comment by niklassaers** [comment]
Hehe, this week became right now. ;-) Thanks for having no dependencies! :-) That made it super-easy to get the Swift Package Manager integrated. Sent pull request #22

**Comment by kwylez** [comment]
@niklassaers this work looks awesome....in addition to your additional comments and code. I'm out of town right now but I'll be in front of my machine this afternoon and merge all of this in

**Comment by niklassaers** [comment]
Awesome, thanks. :-)
