### ISSUE TITLE
Transition To Swift 1.2 Errors

### ISSUE THREAD

**Issue by tbogosia** [GraphStory/neo4j-ios#3]
While transitioning to Swift 1.2, I've found a number of syntactical errors and (after debugging these), general connection failures.

The syntactical errors appear to be mostly related to the inclusion of the "as!" syntax and instantiation of constants with "let".

Once these are resolved, I receive:

```
Error Domain=com.theo.network.error Code=-1 "The operation couldn’t be completed. (com.theo.network.error error -1.)" UserInfo=0x170220f00 {TheoResponse=<NSHTTPURLResponse: 0x170237160> { URL: [MYCYPHERURL]} { status code: 400, headers {
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Length" = 564;
    "Content-Type" = "application/json; charset=UTF-8";
    Date = "Thu, 09 Apr 2015 22:43:03 GMT";
    Server = "nginx/1.7.6";
} }, TheoResponseCode=400, NSLocalizedDescriptionKey=There was an error processing the request}
```
and 

```
Error Domain=com.theo.network.error Code=-1011 "The operation couldn’t be completed. (com.theo.network.error error -1011.)" UserInfo=0x174233f80 {TheoResponse=<NSHTTPURLResponse: 0x170220f00> { URL: [MYCYPHERURL]} { status code: 500, headers {
    "Cache-Control" = "must-revalidate,no-cache,no-store";
    Connection = "keep-alive";
    "Content-Length" = 0;
    "Content-Type" = "text/html; charset=ISO-8859-1";
    Date = "Thu, 09 Apr 2015 22:43:03 GMT";
    Server = "nginx/1.7.6";
} }, TheoResponseCode=500, NSLocalizedDescriptionKey=The response was empty, but you received at valid response code}
```

**Comment by jeremykendall** [comment]
Thanks, @tbogosia.

@kwylez Let me know if you think there's something I should look at on the Graph Story infrastructure side. Nothing jumps out at me.

**Comment by tbogosia** [comment]
Quick update:
printing the data returned is showing 

  "message" : "You have to provide the 'query' parameter.",
  "exception" : "BadInputException",
  "fullname" : "org.neo4j.server.rest.repr.BadInputException",
  "stacktrace" : [ "org.neo4j.server.rest.web.CypherService.cypher(CypherService.java:81)", "java.lang.reflect.Method.invoke(Method.java:606)", "org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)", "org.neo4j.server.extension.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:57)", "java.lang.Thread.run(Thread.java:745)" ]

However, the HTTPBody in request is showing:
{
    params =     {
        fbID = 10203777514982830;
    };
    query = "MATCH (u:User {id:{fbID}})-[:LIKES_ARTIST]->(a:Artist)<-[:LIKES_ARTIST]-(matches:User) WITH DISTINCT matches AS m LIMIT 5 OPTIONAL MATCH (m)-[:LIKES_ARTIST]->(mutual_artists:Artist)<-[:LIKES_ARTIST]-(u:User {id:{fbID}}) OPTIONAL MATCH (m)-[:FRIENDS_WITH]->(mutual_friends:User)<-[:FRIENDS_WITH]-(u:User {id:{fbID}}) RETURN m, COLLECT(distinct mutual_artists) as mutual_artists, COLLECT(distinct mutual_friends) as mutual_friends";
}

However the HTTPBody passed in as NSData is showing:
{"query":"MATCH ... WITH DISTINCT ... OPTIONAL MATCH  ... OPTIONAL MATCH ... RETURN ...","params":{ "..." : "..." }}

Maybe an 'optional' is popping up somewhere?

**Comment by tbogosia** [comment]
Quick update:
printing the data returned is showing

"message" : "You have to provide the 'query' parameter.",
"exception" : "BadInputException",
"fullname" : "org.neo4j.server.rest.repr.BadInputException",
"stacktrace" : [ "org.neo4j.server.rest.web.CypherService.cypher(CypherService.java:81)", "java.lang.reflect.Method.invoke(Method.java:606)", "org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)", "org.neo4j.server.extension.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:57)", "java.lang.Thread.run(Thread.java:745)" ]

However the HTTPBody passed in as NSData is showing:
{"query":"MATCH ... WITH DISTINCT ... OPTIONAL MATCH ... OPTIONAL MATCH ... RETURN ...","params":{ "..." : "..." }}

Maybe an 'optional' is popping up somewhere?

**Comment by kwylez** [comment]
The main issue that with the most recent version of Xcode swift has a ton of new updates and the framework hasn't been updated to reflect this. Updates are in progress.

**Comment by tbogosia** [comment]
Ah, well that's just the worst. Thanks for looking into it!
Please let me know when updates are available if possible.

**Comment by jeremykendall** [comment]
@kwylez :+1:

**Comment by kwylez** [comment]
@tbogosia if you already have some fixes would you mind PR'ing them? In addition, what type of request are trying to make? If there a unit test for that type of request already in the project? If there is then I'll try and track down what is happening and if there isn't then we can add one.

**Comment by tbogosia** [comment]
Absolutely. I'm not near a computer at the moment, but I'll get it done ASAP. The changes are pretty trivial, but it should give you a sense of where I am. In general I'm converting many of the "as" to "as!" and changing the dictionary for loops in each init into more direct instantiations of variables. 

Also, I'm doing a cypher query post. I'm afraid the http body is taking an optional in a string somewhere, which is burying the "query" key, but I'm not very well versed in these connections.

**Comment by tbogosia** [comment]
Hi again, this is embarrassing, but I haven't had a lot of experience with pull requests. I've tried forking and then creating a pull request for my changes but I'm getting some errors with authentication. Any advice? Sorry...

**Comment by jeremykendall** [comment]
@tbogosia I've used the GitHub "How to Fork" documentation more times than I care to mention: https://help.github.com/articles/fork-a-repo/

**Comment by tbogosia** [comment]
@jeremykendall I learn something every day!

**Comment by jeremykendall** [comment]
:+1:

**Comment by kwylez** [comment]
@tbogosia I've pulled your changes to my local repo and made some minor clean up, but more importantly ran the unit tests and everything **passed**

![screen shot 2015-04-14 at 10 54 45 am](https://cloud.githubusercontent.com/assets/233571/7139654/6355f174-e295-11e4-9d61-83fad268592f.png)

With that said can you provide some more information regarding the call you are making that is failing?

I'll be merging the changes into master very shortly

**Comment by kwylez** [comment]
I'm going to close this issue. Go ahead and file another issue for the response error

**Comment by tbogosia** [comment]
@kwylez uh oh. I'll follow up soon. But good to know that's fully resolved. Crosses one possibility off my list.
