### ISSUE TITLE
Pod install - can't find Theo

### ISSUE THREAD

**Issue by pkasson** [GraphStory/neo4j-ios#36]
Here is my pod file ... no joy:

source 'https://github.com/CocoaPods/Specs.git'

platform :osx, '10.11'
use_frameworks!

target 'Test' do

  pod 'SwiftyJSON'  
  pod 'ObjectMapper'    

  pod 'Theo'         # Neo4j

end

**Comment by niklassaers** [comment]
Hi, sorry for the late reply. Try do "pod repo update" before "pod install", when I install your podfile it installs just fine
