### ISSUE TITLE
Any plan for Swift 4 support?

### ISSUE THREAD

**Issue by spencerkohan** [GraphStory/neo4j-ios#42]
I'd love to use this but it's soon to be outdated.

**Comment by niklassaers** [comment]
Yes, Swift 4 support is in the works, both for Theo and its dependencies

**Comment by niklassaers** [comment]
As a few days ago, the 3.x branch supports both 3.x and 4.x. :-)

The upcoming 4.x branch will be Bolt only, btw, so I very much recommend not using the HTTP client for new projects. For legacy projects, we'll do our best to maintain 3.x independent of 4.x
