### ISSUE TITLE
Response Error on Some Calls

### ISSUE THREAD

**Issue by tbogosia** [GraphStory/neo4j-ios#6]
I hadn't had any problems with Theo and connecting to my Neo4j database until I updated to Swift 1.2. Once I did, even after fixing the syntactical errors, I was unable to connect. 

I generally receive 500 and 400 messages while running the app. Digging into the data returned, I've found that I sometimes receive an error:

>{
>"message" : "You have to provide the 'query' parameter.",
>"exception" : "BadInputException",
>  "fullname" : "org.neo4j.server.rest.repr.BadInputException",
>  "stacktrace" : [ "org.neo4j.server.rest.web.CypherService.cypher(CypherService.java:81)", >"java.lang.reflect.Method.invoke(Method.java:606)", "org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)", "org.neo4j.server.extension.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:57)", "java.lang.Thread.run(Thread.java:745)" ]
}

I've tried all of the sample tests, and it seems like some of the reading requests are working and all of the POSTs are not. Here is my results from Unit testing (it crashes):

>Test Suite 'All tests' started at 2015-04-15 20:00:19 +0000
Test Suite 'TheoTests.xctest' started at 2015-04-15 20:00:19 +0000
Test Suite 'Theo_000_RequestTests' started at 2015-04-15 20:00:19 +0000
Test Case '-[TheoTests.Theo_000_RequestTests test_000_successfullyFetchDBMeta]' started.
meta in success Optional(Extensions: [SpatialPlugin: {
    addCQLDynamicLayer = "https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext/SpatialPlugin/graphdb/addCQLDynamicLayer";
    addEditableLayer = "https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext/SpatialPlugin/graphdb/addEditableLayer";
    addGeometryWKTToLayer = "https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext/SpatialPlugin/graphdb/addGeometryWKTToLayer";
    addNodeToLayer = "https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext/SpatialPlugin/graphdb/addNodeToLayer";
    addNodesToLayer = "https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext/SpatialPlugin/graphdb/addNodesToLayer";
    addSimplePointLayer = "https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext/SpatialPlugin/graphdb/addSimplePointLayer";
    findClosestGeometries = "https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext/SpatialPlugin/graphdb/findClosestGeometries";
    findGeometriesInBBox = "https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext/SpatialPlugin/graphdb/findGeometriesInBBox";
    findGeometriesWithinDistance = "https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext/SpatialPlugin/graphdb/findGeometriesWithinDistance";
    getLayer = "https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext/SpatialPlugin/graphdb/getLayer";
    updateGeometryFromWKT = "https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext/SpatialPlugin/graphdb/updateGeometryFromWKT";
}] node: https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/node node_index: https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/index/node relationship_index: https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/index/relationship extensions_info : https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/ext, relationship_types: https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/relationship/types batch: https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/batch cypher: https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/cypher indexes: https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/schema/index constraints: https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/schema/constraint transaction: https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/transaction node_labels: https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/labels neo4j_version: 2.1.7) error nil
Test Case '-[TheoTests.Theo_000_RequestTests test_000_successfullyFetchDBMeta]' passed (0.558 seconds).
Test Case '-[TheoTests.Theo_000_RequestTests test_001_successfullyFetchNode]' started.
/Users/[ME]/Desktop/SYNC/Sync/neo4j-ios/Source/Theo/TheoTests/Theo_000_RequestTests.swift:67: error: -[TheoTests.Theo_000_RequestTests test_001_successfullyFetchNode] : XCTAssertTrue failed - Node data can't be nil
/Users/[ME]/Desktop/SYNC/Sync/neo4j-ios/Source/Theo/TheoTests/Theo_000_RequestTests.swift:68: error: -[TheoTests.Theo_000_RequestTests test_001_successfullyFetchNode] : XCTAssertTrue failed - Meta data can't be nil
/Users/[ME]/Desktop/SYNC/Sync/neo4j-ios/Source/Theo/TheoTests/Theo_000_RequestTests.swift:69: error: -[TheoTests.Theo_000_RequestTests test_001_successfullyFetchNode] : XCTAssertTrue failed - Error must be nil Optional("Error Domain=com.theo.network.error Code=-1011 \"The operation couldn’t be completed. (com.theo.network.error error -1011.)\" UserInfo=0x7ae47030 {NSLocalizedDescriptionKey=The response was empty, but you received at valid response code, TheoResponseCode=404, TheoResponse=<NSHTTPURLResponse: 0x7af8f4b0> { URL: https://neo-552c1f6d3fd5c-364459c455.do-stories.graphstory.com:7473/db/data/node/100 } { status code: 404, headers {\n    \"Access-Control-Allow-Origin\" = \"*\";\n    Connection = \"keep-alive\";\n    \"Content-Length\" = 743;\n    \"Content-Type\" = \"application/json; charset=UTF-8\";\n    Date = \"Wed, 15 Apr 2015 20:00:17 GMT\";\n    Server = \"nginx/1.7.6\";\n} }}")
fatal error: unexpectedly found nil while unwrapping an Optional value

I've been searching for an explanation for a while now and I'm having trouble coming up with anything.

**Comment by tbogosia** [comment]
Oh, also want to add (if it wasn't clear) I ran the unit tests in the included Theo XcodeWorkspace, not in my own project.

**Comment by tbogosia** [comment]
I believe that crash was due to there being no data in my database before, the tests are now reaching test_004_successfullyAddNodeWithOutLabels before crashing. Which makes a lot more sense, since I had believed the GET requests were working and the POST were the problem.

**Comment by tbogosia** [comment]
I've found the problem. The headers set by Theo were being changed somewhere before sending the request. I'm going to try to locate where that's happening, but the easy fix was making sure to send application/json header right before the request went out. 

If I find that it's an error in the code I'll create a pull request, it may have just been a strange problem with my code.

**Comment by kwylez** [comment]
that's very strange. I'll start looking there as well. This is just for your POSTS right?

**Comment by kwylez** [comment]
Put a breakpoint or log the additional headers property in the request class

**Comment by tbogosia** [comment]
Yeah, I added 
```
mutableRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")
```
in the postResource method of Request.swift, where the mutable request is made, and everything was fine afterward. 

It was coming out as application/www-x-form-urlencoded when I checked my data packages going out before. Not sure where the change happened, because in the initial construction it was definitely using /json for the .httpRequest.

**Comment by kwylez** [comment]
I'll create a new branch and if you can issue a PR for this change. It will be a few hours before I get home.

**Comment by tbogosia** [comment]
No problem, will do.

**Comment by kwylez** [comment]
I created a new branch for your to PR to issue/post-header

**Comment by tbogosia** [comment]
Perfect, I'll PR soon

**Comment by tbogosia** [comment]
Hi again Cory,

I'm having a little trouble. I think I executed a cypher query that was
long-running on my database by accident. Now I can't access the database at
all and all of my queries are timing out. I'm guessing that the database is
still attempting to run the other queries and can't respond to my requests.
Is there anything I can do?

Thanks,
Travis

**Comment by jeremykendall** [comment]
Hey @tbogosia, 

Looks like there was indeed an issue with your database. I've restarted the instance and you're back up and running again.

Whenever you think there might be an issue with your database, please shoot an email over to support@graphstory.com. We're more than happy to get that sorted out for you. Thanks!

**Comment by tbogosia** [comment]
Wonderful, thanks Jeremy.
Is the issue something I can avoid in the future? Or just a fluke sort of
thing...

**Comment by jeremykendall** [comment]
Careful query construction and correct indexes and constraints help avoid this situation. Send your query over to support@graphstory.com and we'll take a look at it for you, if you like.

**Comment by tbogosia** [comment]
Alright, thanks Jeremy. It's a complex one that I've been thinking over for
a bit. I'll send it over now.
