### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by buidinhduong** [GraphStory/neo4j-ios#7]
Dear Admin,
I have this issue when trying to run the project. It builds successfully but crash by this following:

==============================================================================
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/buiduong/Library/Developer/Xcode/DerivedData/TestNeo4j-aqdumgntiatrgsbkvvmgvcspnzie/Build/Products/Debug-iphonesimulator/Theo.framework/Theo
  Reason: image not found

===============================================================================

**Comment by kwylez** [comment]
What version of Xcode are you using?

**Comment by buidinhduong** [comment]
Hi,
I am using Xcode 6.3.1 !

**Comment by buidinhduong** [comment]
I have tried this but it is still not working .

Runpath Search Paths is $(inherited) @executable_path/Frameworks
Embedded Content Contains Swift Code is 'Yes'

**Comment by kwylez** [comment]
When was the last time you pulled from the repo? I'm using the same version of Xcode and was able to build the project and the unit tests without issue.

**Comment by buidinhduong** [comment]
Just some hours ago , could you please give me a sample of yours which is a project that embed THEO Framework.

**Comment by buidinhduong** [comment]
Here is my screen :
![screen shot 2015-04-28 at 10 17 10 pm](https://cloud.githubusercontent.com/assets/5101796/7373028/5b26d544-edf4-11e4-8516-c6dce2fd913e.png)

**Comment by kwylez** [comment]
Did you link the framework in your app?
![screen shot 2015-04-29 at 7 32 54 am](https://cloud.githubusercontent.com/assets/233571/7390062/0d0c48fa-ee42-11e4-9a96-86ac1303b8a2.png)

**Comment by kwylez** [comment]
I'm closing this issue since I never heard back on my proposed solution.
